var number = +prompt("Minut oruulna uu");
var number2 = +prompt("Sekund oruulna uu");
var sec,min;
min = number * 60;
alert(min+number2+"sec");
var number = +prompt("Tsag oruulna uu");
var number2 = +prompt("Minut oruulna uu");
var number3 = +prompt("Sekund oruulna uu");
tsag = number * 3600;
min = number2 * 60;
alert(tsag+min+number3+"sec");
var number = +prompt ("Tsag oruulna uu");
var honog,tsag;
honog = number / 24;
tsag = number % 24;
alert(Math.floor(honog)+"honog"+tsag+"tsag");
var number = +prompt ("Honog oruulna uu");
var number2 = +prompt ("Tsag oruulna uu");
honog = number * 24;
alert(honog+number2+"tsag");
var number= +prompt ("Sar oruulna uu");
var jil,sar;
jil = number / 12;
sar = number % 12;
alert(Math.floor(jil)+"jil"+sar+"sar");
var number= +prompt ("Jil oruulna uu");
var number2= +prompt ("Sar oruulna uu");
jil = number * 12;
alert(jil+number2+"sar");